spring:
  application:
    name: bank-Application
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true